version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nestjs_db
      MYSQL_USER: nestjs_user
      MYSQL_PASSWORD: nestjs_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  nest:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '5001:5002'
    depends_on:
      - mysql

volumes:
  mysql_data:
