name: CI

on:
  push:
    branches:
      - staging
      - '7-check-deployment-solutions-and-implement-one' # For test, remove after

jobs:
  hello-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Say Hello CI!
        run: echo "Hello CI!"
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm install
    - run: npm test
    - name: Install Railway
      run: npm i -g @railway/cli
    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.GYMRATS_API_RAILWAY_DEPLOY_TOKEN }}
    - name: Get Deployment URL
      id: get_url
      env:
        RAILWAY_API_PROJECT_ID: ${{ secrets.GYMRATS_API_RAILWAY_PROJECT_ID }}
        RAILWAY_API_TOKEN: ${{ secrets.GYMRATS_API_RAILWAY_DEPLOY_TOKEN }}
      run: |
        DEPLOYMENT_INFO=$(curl -s -H "Authorization: Bearer $RAILWAY_API_TOKEN" https://railway.app/api/v1/projects/$RAILWAY_API_PROJECT_ID/deployments)
        DEPLOYMENT_URL=$(echo $DEPLOYMENT_INFO | jq -r '.latest.deployment.url')
        echo "Deployment URL: $DEPLOYMENT_URL"
